version: "3"

services:
  casepro:
    build:  
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports: 
      - 8000:8000
    links: 
      - redis
      - database
    depends_on: 
      - redis
      - database
      
  casepro_celery_celery:
    image: casepro_casepro
    command: celery worker -A casepro -Q celery -B -n casepro.celery --loglevel=INFO
    depends_on: 
      - redis
      - database
      - casepro

  casepro_celery_sync:
    image: casepro_casepro
    command: celery worker -A casepro -Q sync -n casepro.sync --loglevel=INFO
    depends_on: 
      - redis
      - database
      - casepro

  redis:
    image: redis
    ports: 
      - 6379:6379
    restart: always

  database:
    image: postgres
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=casepro
      - POSTGRES_PASSWORD=nyaruka
      - POSTGRES_DB=casepro
